category_watcher:
    categories:
        - slug: shakes-and-fidget
        - slug: rust
        - slug: counter-strike
        - slug: elden-ring
        - slug: league-of-legends
        - slug: minecraft
        - slug: tom-clancys-rainbow-six-siege
    drops_only: true
    enabled: true
    poll_interval: 2m0s
features:
    claim_drops_startup: true
max_watch_streams: 20
notifications:
    webhook:
        method: POST
priority:
    - STREAK
    - DROPS
    - ORDER
streamer_defaults:
    bet:
        delay: 6
        delay_mode: FROM_END
        max_points: 50000
        minimum_points: 0
        percentage: 5
        percentage_gap: 20
        strategy: SMART
    chat: ONLINE
    claim_drops: true
    claim_moments: true
    community_goals: false
    make_predictions: false
    watch_streak: true
streamers:
    - username: guliveer_
    - username: ohnepixel
    - username: jaskol95
    - username: spartiatix
    - username: tamae_
    - username: officialhyper
    - username: byalli
    - username: n3utr4lsf
